# 
N_WORKERS: 16
VIS_RESULT: True
INPUT_IMG_DIR: "./data/input_img_dir"
LAYOUT_DIR: "./data/layout_dir"
OUTPUT_DIR: "./data/results"
VIS_DIR: "./data/vis"
TMP_DIR: "./tmp"

# ALGORITHM
CROP_W: 250
CROP_H: 250
STEP: 500
LAYOUT_SCALE: [1, 1] # w, h
INPUT_SCALE: [1, 1] # w, h
# READ_CHANNELS: R, G, B, Nir, RGB
READ_CHANNELS: RGB
NUM_MATCHES_THRESH: 100
KP_PAIRS_TO_KP_CROP: 0.5 # 0 < x < 1
FEATURE_EXTRACTOR:
  name: "ASIFT"
  params: {}
MATCHER:
  name: "FLANNMatcher"
  params:
    norm: "L2"
    FLANN_INDEX: 1
    k: 2

# CLAHE: DYN, OFF, ON
CLAHE_MODE: "ON"
CLAHE:
  clipLimit: 128
  tileGridSize: [3, 3]

