version: "3.7`"
services:
 eda_18:
    image: eda_18:latest
    container_name: ${USER}_eda_18
    build:
      shm_size: "16gb"
      dockerfile:  Dockerfile
    volumes:
      - /storage_labs/3050/SavochkinA/work/simple_data/:/app/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 16000000000 # ~16gb
    ports:
      - "7051:22"
    command: >
     bash -c "service ssh start && sleep 100d"